### ISSUE TITLE
Access denied to push up code for PR

### ISSUE THREAD

**Issue by surfdoc** [jupyterhealth/software-documentation#1]
@maryamv or @ryanlovett - I don't think I have permissions for this repo to push up the security.md document. Could you enable permissions for me? Thanks.

**Comment by ryanlovett** [comment]
@surfdoc I'm afraid I don't have permission to add you to the team with access, or to manually add you to the repo itself.

**Comment by maryamv** [comment]
@surfdoc absolutely! I added you to the writers' team.

**Comment by maryamv** [comment]
@ryanlovett I moved you from maintaining to admin.
